#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ren Sato miseria.ren@gmail.com
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans1 = 0
ans2 = 0
ans3 = 0
ans4 = 0

for line in sys.stdin:
    try:
        ans1 += int(line)
        ans2 -= int(line)
        ans3 *= int(line)
        ans4 /= int(line)
    except:
        ans1 += float(line)
        ans2 -= float(line)
        ans3 *= float(line)
        ans4 /= float(line)

print(ans1,ans2,ans3,ans4)
