#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ren Sato miseria.ren@gmail.com
# SPDX-License-Identifier: BSD-3-Clause
import sys
def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans1 = 0

for line in sys.stdin:
    ans1 += tonum(line)

print(ans1)
