#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ren Sato miseria.ren@gmail.com
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans1 = 0
ans2 = 0
for line in sys.stdin:
    try:
        ans1 += int(line)
        ans2 -= int(line)
    except:
        ans1 += float(line)
        ans2 -= float(line)

print(ans1,ans2)
