#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ren Sato miseria.ren@gmail.com
# SPDX-License-Identifier: BSD-3-Clause

import sys
def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans1 = 0
ans2 = 0
ans3 = 1
ans4 = 1
i = 0

for line in sys.stdin:
    ans1 += tonum(line)
    ans2 -= tonum(line)
    ans3 *= tonum(line)
    ans4 /= tonum(line)
    i += 1

    ave = ans1 / i

print(ans1,ans2,ans3,f'{ans4:.10f}',ave)
